### ISSUE TITLE
minimumArrivals

### ISSUE THREAD

**Issue by mmesim** [damb/scdetect#101]
@damb Well, I shared with you the files. Here I'll report the problem. I run the shared example and set `minimumArrivals`: 10. However, when I run `scevent` with the results.scml I received the following message multiple times

```
rejecting automatic origin Origin/20220318161026.734837.31225 (phaseCount: 3 < 10)
```
or 
```
rejecting automatic origin Origin/20220318161026.734837.31225 (phaseCount: 6 < 10)
```

That probably means that there are not 10 picks available, which seems weird. 

I still do not if it `scdetect-cc` or `scevent` problem. 

I didn't include the results.scml to check whether you can fully reproduce the error.

**Comment by damb** [comment]
@mmesim, thanks for reporting.

> That probably means that there are not 10 picks available, which seems weird.

Without having checked the reproducer's configuration yet, I guess that this might be an issue when trying to avoid to associate a single phase to be associated multiple times with a sensor location. This is required in certain configuration scenarios, e.g. given the following detector configuration:

```json
  {
    "detectorId": "detector-01",
    "createArrivals": true,
    "originId": "originId",
    "templatePhase": "Sg",
    "templateWaveformStart": -0.25,
    "templateWaveformEnd": 2,
    "streams": [
      {
        "templateId": "template-01",
        "waveformId": "CH.GRIMS..HHN"
      },
      {
        "templateId": "template-02",
        "waveformId": "CH.GRIMS..HHE"
      }
    ]
  }
```
I.e. in the example above, in order to avoid to associate an `Arrival` with phase `Sg`  twice (regarding the sensor location `CH.GRIMS..`) `scdetect-cc` drops one of the arrivals including the respective pick. This is not ideal, however, AFAIU, in the SeisComP datamodel the relationship `Pick <-> Origin` can be established only by means of an `Arrival`.

Do you have a better idea how to circumvent this issue?

**Comment by mmesim** [comment]
What I do not understand is why I didn't face this problem with the other testing datasets. 

If what you mention above is the case, then it should have happened before. Still thinking about it...

**Comment by damb** [comment]
> If what you mention above is the case, then it should have happened before. Still thinking about it...

- You mean, while using the `"minimumArrivals"` configration parameter, as well?
- Did you check `scevent` logs previously, too?

**Comment by mmesim** [comment]
> You mean, while using the "minimumArrivals" configration parameter, as well?
Yes.

> Did you check scevent logs previously, too?
Yes

**Comment by mmesim** [comment]
I just realized that there was a typo. Instead of writing `ELM0` I wrote `EML0`. :face_exhaling: 

Also, I do not know why `STLM2.HG?` is not in the inventory. Perhaps I did not include acc? I don't remember. 

To conclude, in the case that `scdetect-cc` will not be able to identify  10 phases, what will it do and how is this trackable/manageable in real time application?

**Comment by damb** [comment]
> To conclude, in the case that `scdetect-cc` will not be able to identify 10 phases, what will it do and how is this trackable/manageable in real time application?

Warnings are already issued. Though, in case the `"minimumArrivals"` is configured `scdetect-cc` may not initialize the detector at all. What do you suggest?

**Comment by mmesim** [comment]
Need to think about it.
