### ISSUE TITLE
Sensor orientation mismatch

### ISSUE THREAD

**Issue by damb** [damb/scdetect#8]
The sensor orientation of the template waveform data and the data to be matched might differ. Therefore, always check for the sensor orientation (from the inventory metadata) of the stream to be matched and rotate the template waveform if required (@jfclinton).

**Comment by mmesim** [comment]
I just run into a similar problem. Any smart way to fix this?

**Comment by damb** [comment]
Well, we would need to rotate the template waveform in order to have it aligned with the sensor to be matched. Currently, this feature is not implemented, yet.

I don't see an alternative quick and dirty solution to this.

**Comment by mmesim** [comment]
We might need to rotate the data as well. For example in my case that I load a mseed file that contains the 3 channels i.e RAW2.HH[Z,E,N] we should do
1. Sort the mseed file to be seiscomp-friendly
2. Rotate the waveforms. 

I don't know if this is required for real time application. 

Another thing to keep in mind is the rotation itself. Again, I do not know how the data are rotated in the seiscomp-real time processing, but we should follow exactly the same process.

For now I'll drop testing the horizontals and continue with the Z and P phases.

**Comment by damb** [comment]
Of course, at the time being you could rotate the data to be matched such that the orientation of the data to be matched agrees with the orientation of the sensor the template was extracted from. Though, this approach is applicable for *playback* processing, only.

For real-time processing it is definitely computationally cheaper to rotate the template waveform data, only.  (Actually, I don't see a scenario where it would be required to rotate the real-time data, too. If you are aware of such an example, let me know. Though, it could be implemented by means of the `WaveformOperator` concept.)

**Comment by luca-s** [comment]
@mmesim Let's say you have a S phase picked on the T component  (which you cannot use in `scdetect`). Why don't you create a template at the S time that matches the 3 components Z,E,N instead?  The T component is a projection of the 3 other components anyway, so the cross-correlation on the 3 should perform very similarly.

**Comment by mmesim** [comment]
I think we should clarify a few things. 
First, of all is fundamentally wrong to correlate an N or E channel with the R or T. 

@damb 

> For real-time processing it is definitely computationally cheaper to rotate the template waveform data, only. (Actually, I don't see a scenario where it would be required to rotate the real-time data, too. If you are aware of such an example, let me know. Though, it could be implemented by means of the WaveformOperator concept.)

I think there is a misunderstanding here. You cannot correlate a rotated template with one of the horizontals [N or E]. If I understand correctly, you suggest to rotate the template so the sensor will be H?R,  but the waveform H?N ? That  means that the template channel will match the template channel in the **events.xml**, the S-phase is picked on the H?R, and the raw data will match the channel listed in **stations.xml** file, right? If this is the case then it is not the right way of doing it. 

I see two possible scenarios. (i) On the fly rotate both the template and the raw waveform. (ii) (@luca-s's suggestion) Ignore the rotation, keep the phase arrival time, and correlate H?N with HHN, and H?E with H?E. @luca-s  suggested to redirect somehow the channel, if it doesn't find an H?R in the station inventory then look for an H?N, and similar with E and T. 

@luca-s 

>  Let's say you have a S phase picked on the T component (which you cannot use in scdetect). Why don't you create a template at the S time that matches the 3 components Z,E,N instead? 

Yes, you can do that. The time of course will not correspond exactly to the S pick but we usually start the correlation a bit before the catalog pick. Also this is the case if the pick is in the E and we use the same time to N. The arrivals should differ by a little due to anisotropy.

> The T component is a projection of the 3 other components anyway, so the cross-correlation on the 3 should perform very similarly.

The xcorr will not be affected because will start the correlation before the phase time, and the xcorr will find the correct time for the maximum CCC.

**Comment by damb** [comment]
> I think there is a misunderstanding here.

Therefore, I asked you to give an example ;). When opening the issue, I didn't have an ZNE -> ZRT projection in mind. Rather a rotation in order to align the sensor orientation recording the template waveform with the sensor orientation recording the data to be matched.

> You cannot correlate a rotated template with one of the horizontals [N or E]. If I understand correctly, you suggest to rotate the template so the sensor will be H?R, but the waveform H?N ?

Of course, the orientation of the template waveform and the data to be matched must agree.

> I see two possible scenarios. (i) On the fly rotate both the template and the raw waveform. (ii) (@luca-s's suggestion) Ignore the rotation, keep the phase arrival time, and correlate H?N with HHN, and H?E with H?E. @luca-s suggested to redirect somehow the channel, if it doesn't find an H?R in the station inventory then look for an H?N, and similar with E and T.

(ii) is already implemented. It is only the arrival time (i.e. the pick time) which is taken into account. Please, refer also to the discussion in #3. I hope it is clearer now.

**Comment by mmesim** [comment]
I'm very happy that we clarified it @damb. 

To conclude, it was a misunderstanding on my end but it is very clear to me now that you are using the pick times and do not associate the channels. 

A last comment, I do not think that the rotation is needed.  My concern was that if we rotate to a preliminary epicenter while picking, then that location might differ for the final NLL solution. In that case I have noticed that even a couple of degrees difference in azimuth will make a notable difference on the amplitudes of the rotated waveforms. It would be better, and of course less complicated, if we do not rotate.

**Comment by damb** [comment]
> A last comment, I do not think that the rotation is needed. My concern was that if we rotate to a preliminary epicenter while picking, then that location might differ for the final NLL solution. In that case I have noticed that even a couple of degrees difference in azimuth will make a notable difference on the amplitudes of the rotated waveforms. It would be better, and of course less complicated, if we do not rotate.

That's a good point. I agree with that.

I'll close this issue for now. Please, reopen if required.
